# Generated by Django 3.1.2 on 2020-10-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
