# Generated by Django 3.1.2 on 2020-10-19 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySerializer',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.property')),
            ],
            bases=('properties.property',),
        ),
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='long',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
