# Generated by Django 3.1.2 on 2020-10-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20201020_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photos',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
