# Generated by Django 3.1.2 on 2020-10-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20201020_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='property',
            name='photo1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='photo2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='photo3',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='photo4',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='photo5',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='photo6',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
